# MongoDB
MONGODB_URI = "mongodb+srv://adminDB:a25120913@cluster1.eqoejsj.mongodb.net/"

PORTAL_LOUVOR = "portal_louvor"
PORTAL_LOUVOR_DEV = "portal_louvor_dev"

# ===============================
# Admin
# ===============================
[admin]
senha = "admin.ibr"

# ===============================
# Ministro
# ===============================
[ministro]
senha = "ministracao.ibr"